#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Call-an-Expert MVP Platform

set -e

echo "========================================"
echo "Call-an-Expert Development Environment"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}✗ $name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo ""
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

# Check for required tools
check_requirements() {
    echo "Checking requirements..."

    if ! command -v node &> /dev/null; then
        echo -e "${RED}✗ Node.js is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

    if ! command -v npm &> /dev/null; then
        echo -e "${RED}✗ npm is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ npm $(npm --version)${NC}"

    if ! command -v npx &> /dev/null; then
        echo -e "${RED}✗ npx is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ npx available${NC}"

    echo ""
}

# ============================================
# PHASE 1: SUPABASE (Database)
# ============================================
start_supabase() {
    echo "----------------------------------------"
    echo "Starting Supabase (Database)..."
    echo "----------------------------------------"

    if [ -d "supabase" ]; then
        cd supabase
        if npx supabase status &> /dev/null; then
            echo -e "${YELLOW}⚠ Supabase already running${NC}"
        else
            npx supabase start &
        fi
        cd ..
        wait_for_service 54321 "Supabase API"
    else
        echo -e "${YELLOW}⚠ Supabase directory not found. Skipping...${NC}"
        echo "  Run 'npx supabase init' to create it."
    fi
    echo ""
}

# ============================================
# PHASE 2: NEXT.JS WEB APP
# ============================================
start_web() {
    echo "----------------------------------------"
    echo "Starting Next.js Web App..."
    echo "----------------------------------------"

    if [ -d "web" ]; then
        cd web
        if [ ! -d "node_modules" ]; then
            echo "Installing web dependencies..."
            npm install
        fi

        # Check for .env.local
        if [ ! -f ".env.local" ]; then
            echo -e "${YELLOW}⚠ .env.local not found${NC}"
            echo "  Copy .env.example to .env.local and configure it."
        fi

        npm run dev &
        cd ..
        wait_for_service 3000 "Next.js Web App"
    else
        echo -e "${YELLOW}⚠ Web directory not found. Skipping...${NC}"
        echo "  Run the Phase 2 subtasks to create it."
    fi
    echo ""
}

# ============================================
# PHASE 3: SOCKET.IO SERVER
# ============================================
start_server() {
    echo "----------------------------------------"
    echo "Starting Socket.io Server..."
    echo "----------------------------------------"

    if [ -d "server" ]; then
        cd server
        if [ ! -d "node_modules" ]; then
            echo "Installing server dependencies..."
            npm install
        fi
        npm run dev &
        cd ..
        wait_for_service 3001 "Socket.io Server"
    else
        echo -e "${YELLOW}⚠ Server directory not found. Skipping...${NC}"
        echo "  Run the Phase 7 subtasks to create it."
    fi
    echo ""
}

# ============================================
# PHASE 4: CHROME EXTENSION BUILD
# ============================================
build_extension() {
    echo "----------------------------------------"
    echo "Building Chrome Extension..."
    echo "----------------------------------------"

    if [ -d "extension" ]; then
        cd extension
        if [ ! -d "node_modules" ]; then
            echo "Installing extension dependencies..."
            npm install
        fi
        npm run build
        cd ..
        echo -e "${GREEN}✓ Chrome extension built${NC}"
        echo "  Load unpacked at chrome://extensions"
        echo "  Select the extension/dist folder"
    else
        echo -e "${YELLOW}⚠ Extension directory not found. Skipping...${NC}"
        echo "  Run the Phase 4 subtasks to create it."
    fi
    echo ""
}

# ============================================
# STRIPE WEBHOOK LISTENER (Local Dev)
# ============================================
start_stripe_listener() {
    echo "----------------------------------------"
    echo "Starting Stripe Webhook Listener..."
    echo "----------------------------------------"

    if command -v stripe &> /dev/null; then
        stripe listen --forward-to localhost:3000/api/webhook/stripe &
        echo -e "${GREEN}✓ Stripe webhook listener started${NC}"
    else
        echo -e "${YELLOW}⚠ Stripe CLI not installed${NC}"
        echo "  Install with: brew install stripe/stripe-cli/stripe"
        echo "  Or download from: https://stripe.com/docs/stripe-cli"
    fi
    echo ""
}

# ============================================
# MAIN EXECUTION
# ============================================

check_requirements

echo "========================================"
echo "Starting Services..."
echo "========================================"
echo ""

# Start services in order
start_supabase
start_web
start_server
build_extension
start_stripe_listener

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Web App:         http://localhost:3000"
echo "  Supabase API:    http://localhost:54321"
echo "  Supabase Studio: http://localhost:54323"
echo "  Socket.io:       http://localhost:3001"
echo ""
echo "Chrome Extension:"
echo "  1. Open chrome://extensions"
echo "  2. Enable 'Developer mode'"
echo "  3. Click 'Load unpacked'"
echo "  4. Select extension/dist folder"
echo ""
echo "Environment Variables Needed:"
echo "  - NEXT_PUBLIC_SUPABASE_URL"
echo "  - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "  - SUPABASE_SERVICE_ROLE_KEY"
echo "  - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "  - STRIPE_SECRET_KEY"
echo "  - STRIPE_WEBHOOK_SECRET"
echo "  - NEXT_PUBLIC_SOCKET_URL"
echo ""
echo -e "${GREEN}Press Ctrl+C to stop all services${NC}"
echo ""

# Keep script running
wait
